"""job_bundle.pyにmolecules追加できてないじゃーん2

Revision ID: 3d75994f8028
Revises: 77c6c4bc4cd1
Create Date: 2025-07-24 20:01:48.837586

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3d75994f8028"
down_revision: Union[str, Sequence[str], None] = "77c6c4bc4cd1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "molecules",  # テーブル名
        "job_bundle_id",  # カラム名
        existing_type=sa.Integer(),
        nullable=False,  # NOT NULL に変更
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "molecules", "job_bundle_id", existing_type=sa.Integer(), nullable=True
    )  # ### end Alembic commands ###
