"""server_credentialモデルのpassword_encryptedおよびssh_key_encryptedをnullableに変更

Revision ID: 4bab0f30f698
Revises: 1247c7b71885
Create Date: 2025-07-26 18:32:33.495143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bab0f30f698'
down_revision: Union[str, Sequence[str], None] = '1247c7b71885'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('server_credentials', 'password_encrypted',
               existing_type=sa.VARCHAR(length=512),
               nullable=True,
               existing_comment='Fernet 暗号化済みパスワード')
    op.alter_column('server_credentials', 'ssh_key_encrypted',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_comment='Fernet 暗号化済み秘密鍵')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('server_credentials', 'ssh_key_encrypted',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_comment='Fernet 暗号化済み秘密鍵')
    op.alter_column('server_credentials', 'password_encrypted',
               existing_type=sa.VARCHAR(length=512),
               nullable=False,
               existing_comment='Fernet 暗号化済みパスワード')
    # ### end Alembic commands ###
