"""job_bundle.pyにmolecules追加できてないじゃーん

Revision ID: 77c6c4bc4cd1
Revises: f85266e12205
Create Date: 2025-07-24 19:50:20.757282

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "77c6c4bc4cd1"
down_revision: Union[str, Sequence[str], None] = "f85266e12205"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # molecules テーブルに job_bundle_id カラムを追加
    op.add_column(
        "molecules",
        sa.Column(
            "job_bundle_id",
            sa.Integer(),
            nullable=True,
        ),
    )
    # 外部キー制約を追加
    op.create_foreign_key(
        "fk_molecules_job_bundle_id",  # 制約名
        "molecules",  # 子テーブル名
        "job_bundles",  # 親テーブル名
        ["job_bundle_id"],  # 子側カラム
        ["id"],  # 親側カラム
    )  # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # downgrade では逆順で外部キー制約とカラムを削除
    op.drop_constraint("fk_molecules_job_bundle_id", "molecules", type_="foreignkey")
    op.drop_column("molecules", "job_bundle_id")  # ### end Alembic commands ###
