"""カラム名が変わっちゃった。job_bundle_idからbundle_idへ

Revision ID: 9060e2bb8c37
Revises: 3d75994f8028
Create Date: 2025-07-24 20:18:50.274135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9060e2bb8c37'
down_revision: Union[str, Sequence[str], None] = '3d75994f8028'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_molecules_job_bundle_id'), 'molecules', type_='foreignkey')
    op.drop_column('molecules', 'job_bundle_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('molecules', sa.Column('job_bundle_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_molecules_job_bundle_id'), 'molecules', 'job_bundles', ['job_bundle_id'], ['id'])
    # ### end Alembic commands ###
