"""initial schema

Revision ID: 9647b47d8a96
Revises: 
Create Date: 2025-07-13 22:51:06.029821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9647b47d8a96'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('local_base_dir', sa.String(length=512), nullable=False),
    sa.Column('remote_base_dir', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('job_bundles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('calc_type_name', sa.String(length=50), nullable=False),
    sa.Column('theory_level', sa.String(length=50), nullable=False),
    sa.Column('basis_set', sa.String(length=50), nullable=False),
    sa.Column('solvent_model', sa.String(length=50), nullable=True),
    sa.Column('solvent_name', sa.String(length=50), nullable=True),
    sa.Column('mem_gb', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('nproc_shared', sa.Integer(), nullable=True),
    sa.Column('additional_keywords', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('server_credentials',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_encrypted', sa.String(), nullable=True),
    sa.Column('ssh_key_path', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('molecules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_bundle_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('charge', sa.SmallInteger(), nullable=False),
    sa.Column('multiplicity', sa.SmallInteger(), nullable=False),
    sa.Column('atom_count', sa.Integer(), nullable=False),
    sa.Column('local_gjf_path', sa.String(length=512), nullable=False),
    sa.Column('input_xyz_coords', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_bundle_id'], ['job_bundles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('molecule_id', sa.String(), nullable=False),
    sa.Column('gaussian_job_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('remote_job_dir_path', sa.String(length=512), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('last_log_update_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['molecule_id'], ['molecules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_summary_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('final_energy_hartree', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('final_energy_zpe_hartree', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('final_energy_h_hartree', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('final_energy_g_hartree', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('homo_energy_ev', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.Column('lumo_energy_ev', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.Column('band_gap_ev', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.Column('lowest_excitation_energy_ev', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.Column('lowest_oscillator_strength', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_summary_results')
    op.drop_table('jobs')
    op.drop_table('molecules')
    op.drop_table('server_credentials')
    op.drop_table('job_bundles')
    op.drop_table('users')
    # ### end Alembic commands ###
