"""ちょっとへんこう

Revision ID: dcdc1fcb26e8
Revises: ca271f6e5612
Create Date: 2025-07-22 22:29:07.787092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dcdc1fcb26e8'
down_revision: Union[str, Sequence[str], None] = 'ca271f6e5612'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('server_credentials', 'host',
               existing_type=sa.VARCHAR(length=100),
               comment='ホスト名',
               existing_nullable=False)
    op.alter_column('server_credentials', 'username',
               existing_type=sa.VARCHAR(length=100),
               comment='SSH ユーザー名',
               existing_nullable=False)
    op.alter_column('server_credentials', 'password_encrypted',
               existing_type=sa.VARCHAR(length=512),
               nullable=False,
               existing_comment='Fernet 暗号化済みパスワード')
    op.alter_column('server_credentials', 'ssh_key_encrypted',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_comment='Fernet 暗号化済み秘密鍵')
    op.alter_column('server_credentials', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='登録日時',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('server_credentials', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='登録日時',
               existing_nullable=False)
    op.alter_column('server_credentials', 'ssh_key_encrypted',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_comment='Fernet 暗号化済み秘密鍵')
    op.alter_column('server_credentials', 'password_encrypted',
               existing_type=sa.VARCHAR(length=512),
               nullable=True,
               existing_comment='Fernet 暗号化済みパスワード')
    op.alter_column('server_credentials', 'username',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='SSH ユーザー名',
               existing_nullable=False)
    op.alter_column('server_credentials', 'host',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='ホスト名',
               existing_nullable=False)
    # ### end Alembic commands ###
